name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Read charts.yaml
        id: get-version
        run: echo "::set-output name=version::$(cat ./charts/hello-world/Chart.yaml | grep '^appVersion:' | awk '{print $2}')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-example:${{ steps.get-version.outputs.version }}, ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-example:${{ steps.get-version.outputs.version }}